/*
 * HelpFrame.java
 *
 * Created on December 11, 2006, 9:54 PM
 */

package org.redneck.persistinator.gui;

/**
 *
 * @author  Robb
 */
public class HelpFrame extends javax.swing.JFrame {

    private java.util.Hashtable contents = null;
    
    /** Creates new form HelpFrame */
    public HelpFrame() {
        java.util.Hashtable prj = new java.util.Hashtable();
        prj.put("Creating a Project", "");
        prj.put("Opening a Project", "");
        prj.put("Saving a Project", "");
        prj.put("What is a Project?", "");
        
        java.util.Hashtable desc = new java.util.Hashtable();
        desc.put("How to describe a database?", "");
        desc.put("What is describing a database?", "");
        desc.put("Saving a described database", "");
        
        java.util.Hashtable gen = new java.util.Hashtable();
        gen.put("How to generate code", "");
        gen.put("What code gets generated?", "");
        gen.put("Can I customize the generated code?", "");
        gen.put("What are Velocity templates?", "");
        gen.put("Customizing Velocity templates?", "");
        
        contents = new java.util.Hashtable();
        contents.put("Projects", prj);
        contents.put("Describing Database",desc);
        contents.put("Code Generation",gen);
        contents.put("Custom Queries","");
        contents.put("Running Queries","");
        
        
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        helpTree = new javax.swing.JTree(contents);
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setTitle("DAO Generator Help");
        setName("helpFrame");
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Help Contents");
        getContentPane().add(jLabel1, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.X_AXIS));

        jSplitPane1.setOneTouchExpandable(true);
        jScrollPane1.setViewportView(helpTree);

        jSplitPane1.setLeftComponent(jScrollPane1);

        jTextPane1.setText("Help Contents Here");
        jScrollPane2.setViewportView(jTextPane1);

        jSplitPane1.setRightComponent(jScrollPane2);

        jPanel1.add(jSplitPane1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HelpFrame().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree helpTree;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
    
}
