/*
 * MethodEditorFrame.java
 *
 * Created on January 5, 2007, 7:29 PM
 */

package org.redneck.persistinator.gui;

import org.redneck.persistinator.log.SimpleLogger;
import org.redneck.persistinator.meta.AbstractTable;
import org.redneck.persistinator.meta.Table;
import org.redneck.persistinator.meta.userdef.CustomMethod;

/**
 *
 * @author  Robb
 */
public class MethodEditorFrame extends javax.swing.JFrame {
    
    AbstractTable dbTable = null;
    NewMethodFrame parent = null;
    
    /** Creates new form MethodEditorFrame */
    public MethodEditorFrame(NewMethodFrame parent, AbstractTable dbTable) {
        this.dbTable = dbTable;
        this.parent = parent;
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        methodNamePanel = new javax.swing.JPanel();
        methodNameLabel = new javax.swing.JLabel();
        methodNameInput = new javax.swing.JTextField();
        methodSignaturePanel = new javax.swing.JPanel();
        methodSignatureLabel = new javax.swing.JLabel();
        methodSignatureInput = new javax.swing.JTextField();
        methodBodyPanel = new javax.swing.JPanel();
        methodBodyLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        methodBodyIjnput = new javax.swing.JEditorPane();
        jPanel1 = new javax.swing.JPanel();
        saveButton = new javax.swing.JButton();

        setTitle("Method Editor");
        setAlwaysOnTop(true);
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        methodNameLabel.setLabelFor(methodNameInput);
        methodNameLabel.setText("Method Name");
        methodNamePanel.add(methodNameLabel);

        methodNameInput.setColumns(20);
        methodNameInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                methodNameInputKeyTyped(evt);
            }
        });

        methodNamePanel.add(methodNameInput);

        jPanel2.add(methodNamePanel);

        methodSignaturePanel.setLayout(new java.awt.GridLayout(2, 2));

        methodSignatureLabel.setLabelFor(methodSignatureInput);
        methodSignatureLabel.setText("Method Signature");
        methodSignaturePanel.add(methodSignatureLabel);

        methodSignaturePanel.add(methodSignatureInput);

        jPanel2.add(methodSignaturePanel);

        methodBodyPanel.setLayout(new java.awt.BorderLayout());

        methodBodyLabel.setLabelFor(methodBodyIjnput);
        methodBodyLabel.setText("Method Body");
        methodBodyPanel.add(methodBodyLabel, java.awt.BorderLayout.NORTH);

        methodBodyIjnput.setText("// don't inlude the open and close brackets for method");
        methodBodyIjnput.setMinimumSize(new java.awt.Dimension(106, 100));
        methodBodyIjnput.setPreferredSize(new java.awt.Dimension(106, 400));
        jScrollPane2.setViewportView(methodBodyIjnput);

        methodBodyPanel.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel2.add(methodBodyPanel);

        jScrollPane1.setViewportView(jPanel2);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        saveButton.setMnemonic('v');
        saveButton.setText("Save");
        saveButton.setToolTipText("Save this method");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        jPanel1.add(saveButton);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        SimpleLogger.log("Adding new custom method " + this.methodNameInput.getText());
        SimpleLogger.log(this.methodSignatureInput.getText());
        SimpleLogger.log(this.methodBodyIjnput.getText());
        CustomMethod cm = new CustomMethod();
        cm.setMethodBody(this.methodBodyIjnput.getText());
        cm.setMethodName(this.methodNameInput.getText());
        cm.setMethodSignature(this.methodSignatureInput.getText());
        if (dbTable.getCustomMethods().contains(cm)) {
            dbTable.getCustomMethods().remove(cm);
        }
        dbTable.getCustomMethods().add(cm);
        this.setVisible(false);
        parent.refreshView();
    }//GEN-LAST:event_saveButtonActionPerformed
    
    private void methodNameInputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_methodNameInputKeyTyped
// TODO make sure it's not blank and then create new method and enable buttons for adding params
        String newVal = this.methodNameInput.getText();
        if (!"".equals(newVal)) {
            //enable buttons
        }
    }//GEN-LAST:event_methodNameInputKeyTyped
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MethodEditorFrame(null, new Table()).setVisible(true);
            }
        });
    }
    
    public void setCustomMethod(CustomMethod editMethod) {
        this.methodBodyIjnput.setText(editMethod.getMethodBody());
        this.methodNameInput.setText(editMethod.getMethodName());
        this.methodSignatureInput.setText(editMethod.getMethodSignature());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JEditorPane methodBodyIjnput;
    private javax.swing.JLabel methodBodyLabel;
    private javax.swing.JPanel methodBodyPanel;
    private javax.swing.JTextField methodNameInput;
    private javax.swing.JLabel methodNameLabel;
    private javax.swing.JPanel methodNamePanel;
    private javax.swing.JTextField methodSignatureInput;
    private javax.swing.JLabel methodSignatureLabel;
    private javax.swing.JPanel methodSignaturePanel;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
    
}
